/**
 * Proxy Finder — Data Loader
 * 
 * Fetches JSON data files from the GitHub Pages repository.
 * All data is generated by the Python scraper and stored alongside the site.
 * 
 * Data files:
 *   - proxy.json        (all active configs, up to 1000)
 *   - fastest.json      (top 50 by lowest latency)
 *   - recommendations.json  (top 50 by trust grade A)
 *   - leaderboard.json  (top 30 sources by trust)
 *   - stats.json        (engine statistics)
 *   - system/feed.json  (update feed)
 *   - system/health.json (system health status)
 * 
 * @version 1.0.0
 * @date 2026-06
 */

(function () {
  'use strict';

  // Base path for data files (relative to the proxy-finder page)
  var DATA_BASE_PATH = '../../../../data/proxy-finder/';
  var SYSTEM_BASE_PATH = '../../../../data/system/';

  // Cache for loaded data
  var dataCache = {};
  var cacheTimestamps = {};

  // Cache TTL in milliseconds (5 minutes)
  var CACHE_TTL = 5 * 60 * 1000;

  /**
   * Fetch a JSON file with caching.
   * @param {string} url — Full URL or relative path
   * @param {boolean} forceRefresh — Bypass cache
   * @returns {Promise<Object>}
   */
  function fetchJSON(url, forceRefresh) {
    var cacheKey = url;
    var now = Date.now();

    // Return cached data if still fresh
    if (!forceRefresh && dataCache[cacheKey] && (now - cacheTimestamps[cacheKey]) < CACHE_TTL) {
      return Promise.resolve(dataCache[cacheKey]);
    }

    return fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        'Cache-Control': 'no-cache'
      }
    })
    .then(function (response) {
      if (!response.ok) {
        throw new Error('Failed to load ' + url + ': HTTP ' + response.status);
      }
      return response.json();
    })
    .then(function (data) {
      // Update cache
      dataCache[cacheKey] = data;
      cacheTimestamps[cacheKey] = now;
      return data;
    })
    .catch(function (error) {
      console.warn('Data load warning for ' + url + ':', error.message);
      // Return cached data if available, even if expired
      if (dataCache[cacheKey]) {
        return dataCache[cacheKey];
      }
      throw error;
    });
  }

  /**
   * Load all proxy data files.
   * @param {boolean} forceRefresh
   * @returns {Promise<Object>} — { proxies, fastest, recommendations, leaderboard, stats, feed, health }
   */
  function loadAllData(forceRefresh) {
    var promises = {
      proxies: fetchJSON(DATA_BASE_PATH + 'proxy.json', forceRefresh),
      fastest: fetchJSON(DATA_BASE_PATH + 'fastest.json', forceRefresh),
      recommendations: fetchJSON(DATA_BASE_PATH + 'recommendations.json', forceRefresh),
      leaderboard: fetchJSON(DATA_BASE_PATH + 'leaderboard.json', forceRefresh),
      stats: fetchJSON(DATA_BASE_PATH + 'stats.json', forceRefresh),
      feed: fetchJSON(SYSTEM_BASE_PATH + 'feed.json', forceRefresh),
      health: fetchJSON(SYSTEM_BASE_PATH + 'health.json', forceRefresh)
    };

    // Use Promise.allSettled so one failure doesn't block everything
    return new Promise(function (resolve) {
      var results = {};
      var keys = Object.keys(promises);
      var completed = 0;
      var hasAnyData = false;

      keys.forEach(function (key) {
        promises[key]
          .then(function (data) {
            results[key] = data;
            hasAnyData = true;
          })
          .catch(function (error) {
            console.warn('Could not load ' + key + ':', error.message);
            results[key] = null;
          })
          .finally(function () {
            completed++;
            if (completed === keys.length) {
              if (!hasAnyData) {
                results._error = 'No data files could be loaded. Please check that the proxy finder scraper has been run.';
              }
              resolve(results);
            }
          });
      });
    });
  }

  /**
   * Load only the main proxy list (for faster initial load).
   * @param {boolean} forceRefresh
   * @returns {Promise<Array>}
   */
  function loadProxies(forceRefresh) {
    return fetchJSON(DATA_BASE_PATH + 'proxy.json', forceRefresh);
  }

  /**
   * Load recommendations (Grade A configs).
   * @param {boolean} forceRefresh
   * @returns {Promise<Array>}
   */
  function loadRecommendations(forceRefresh) {
    return fetchJSON(DATA_BASE_PATH + 'recommendations.json', forceRefresh);
  }

  /**
   * Load the fastest configs.
   * @param {boolean} forceRefresh
   * @returns {Promise<Array>}
   */
  function loadFastest(forceRefresh) {
    return fetchJSON(DATA_BASE_PATH + 'fastest.json', forceRefresh);
  }

  /**
   * Load leaderboard data.
   * @param {boolean} forceRefresh
   * @returns {Promise<Array>}
   */
  function loadLeaderboard(forceRefresh) {
    return fetchJSON(DATA_BASE_PATH + 'leaderboard.json', forceRefresh);
  }

  /**
   * Load engine stats.
   * @param {boolean} forceRefresh
   * @returns {Promise<Object>}
   */
  function loadStats(forceRefresh) {
    return fetchJSON(DATA_BASE_PATH + 'stats.json', forceRefresh);
  }

  /**
   * Load system feed.
   * @param {boolean} forceRefresh
   * @returns {Promise<Array>}
   */
  function loadFeed(forceRefresh) {
    return fetchJSON(SYSTEM_BASE_PATH + 'feed.json', forceRefresh);
  }

  /**
   * Load system health status.
   * @param {boolean} forceRefresh
   * @returns {Promise<Object>}
   */
  function loadHealth(forceRefresh) {
    return fetchJSON(SYSTEM_BASE_PATH + 'health.json', forceRefresh);
  }

  /**
   * Clear all cached data.
   */
  function clearCache() {
    dataCache = {};
    cacheTimestamps = {};
  }

  /**
   * Get the timestamp of when a specific data file was loaded.
   * @param {string} key — 'proxies', 'fastest', 'recommendations', etc.
   * @returns {number|null} — Timestamp in ms or null
   */
  function getLoadTimestamp(key) {
    var cacheKey = DATA_BASE_PATH + (key === 'feed' || key === 'health' ? '../system/' : '') + key + '.json';
    if (key === 'proxies') cacheKey = DATA_BASE_PATH + 'proxy.json';
    if (key === 'fastest') cacheKey = DATA_BASE_PATH + 'fastest.json';
    if (key === 'recommendations') cacheKey = DATA_BASE_PATH + 'recommendations.json';
    if (key === 'leaderboard') cacheKey = DATA_BASE_PATH + 'leaderboard.json';
    if (key === 'stats') cacheKey = DATA_BASE_PATH + 'stats.json';
    if (key === 'feed') cacheKey = SYSTEM_BASE_PATH + 'feed.json';
    if (key === 'health') cacheKey = SYSTEM_BASE_PATH + 'health.json';
    return cacheTimestamps[cacheKey] || null;
  }

  // ============================================
  // PUBLIC API
  // ============================================

  window.ProxyDataLoader = {
    loadAllData: loadAllData,
    loadProxies: loadProxies,
    loadRecommendations: loadRecommendations,
    loadFastest: loadFastest,
    loadLeaderboard: loadLeaderboard,
    loadStats: loadStats,
    loadFeed: loadFeed,
    loadHealth: loadHealth,
    clearCache: clearCache,
    getLoadTimestamp: getLoadTimestamp,
    DATA_BASE_PATH: DATA_BASE_PATH,
    SYSTEM_BASE_PATH: SYSTEM_BASE_PATH
  };

})();
